### ISSUE TITLE
Sort medias by date

### ISSUE THREAD

**Issue by Mement0o** [vincent-peugnet/wcms#67]
Would it be possible to give a date of upload to media? and print folder content sorted by date

**Comment by vincent-peugnet** [comment]
the function is of course interesting, but, if I haven't worked on it, it's because I'm a bit scare of it haha. I'm not sure of how to do it..

I need to checkout PHP docs about it. I don't know if there are multiple dates like "last edit", or "creation date". Or if I have to care about différents file systems...

@n-peugnet , if you have already had to use this kind of file info, I'm interested ?!

**Comment by n-peugnet** [comment]
In your case the modification date should be the same as the upload date. So `filemtime()` should do the job.

If you are already using the higher level fileiterators you won't need this function as you should be able to get this info from the "file object" you get.
